# test:
#     path: /test/{age<\d+>?0}
#     controller: App\Controller\TestController::test
#     methods: [POST, GET]
    # pour le controle de host depuis lequel on peut acceder
    # host: localhost 
    # schemes: [https, http]
    # {subdomain}monsite.com

    # defaults:
    #     age: 0
    # requirements:
    #     age: \d+
    # \d+ c'est un parametre numerique avec plusieur ou un cheffre
    # soit on ecrit les parametres entres {} dans path {age<\d+>?0}, soit on fait les lignes avec default et requirements